[package]
edition = "2021"
name = "parser"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = { workspace = true }
lsp-types = { workspace = true, features = ["proposed"] }
rowan = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
