[package]
name = "ccls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parser = { workspace = true }
vfs = { workspace = true }
syntax = { workspace = true }

rowan = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true, features = ["proposed"] }

serde_json = { workspace = true }
serde = { workspace = true, features = ["derive"] }

anyhow = { workspace = true }
dashmap = { workspace = true }
path-absolutize = { workspace = true }

[dev-dependencies]
insta = { workspace = true, features = ["yaml"] }
