//! Top-level definitions: `template`, `function`, and `bus`. These share the parser's
//! `definition_body` grammar (`name (params)? block`), so their typed accessors are identical in
//! shape and generated by macros.

use parser::token_kind::TokenKind;
use parser::token_kind::TokenKind::*;
use rowan::ast::{support, AstNode};

use crate::node::{CircomLanguage, SyntaxNode};

use super::block::{AstBlock, AstStatementList};
use super::name::{AstIdentifier, AstParameterList, Named};

macro_rules! impl_name_node {
    ($name:ty) => {
        impl $name {
            pub fn name(&self) -> Option<AstIdentifier> {
                support::child(self.syntax())
            }
        }
        impl Named for $name {
            fn identifier(&self) -> Option<AstIdentifier> {
                self.name()
            }
        }
    };
}

macro_rules! impl_definition_body {
    ($def:ty, $name:ty) => {
        impl $def {
            pub fn name(&self) -> Option<$name> {
                support::child(self.syntax())
            }
            pub fn body(&self) -> Option<AstBlock> {
                support::child(self.syntax())
            }
            pub fn parameter_list(&self) -> Option<AstParameterList> {
                support::child(self.syntax())
            }
            pub fn statements(&self) -> Option<AstStatementList> {
                self.body().and_then(|b| b.statement_list())
            }
        }
        impl Named for $def {
            fn identifier(&self) -> Option<AstIdentifier> {
                self.name().and_then(|n| n.name())
            }
        }
    };
}

// --- template ----------------------------------------------------------------

ast_node!(AstTemplateName, TemplateName);
impl_name_node!(AstTemplateName);

ast_node!(AstTemplateDef, TemplateDef);
impl_definition_body!(AstTemplateDef, AstTemplateName);

// --- function ----------------------------------------------------------------

ast_node!(AstFunctionName, FunctionName);
impl_name_node!(AstFunctionName);

ast_node!(AstFunctionDef, FunctionDef);
impl_definition_body!(AstFunctionDef, AstFunctionName);

// --- bus ---------------------------------------------------------------------

ast_node!(AstBusName, BusName);
impl_name_node!(AstBusName);

ast_node!(AstBusDef, BusDef);
impl_definition_body!(AstBusDef, AstBusName);
